apiRules:
- include:
    uidRegex: ^nickmaltbie\.TestUtilsUnity
    type: Namespace
- include:
    uidRegex: ^nickmaltbie\.TestUtilsUnity\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace